### PR TITLE
Add error handling for FAILURE and NOT_FOUND status

### PR DESCRIPTION
**Pull request by leonluc-dev**
In some cases upload errors noted in the response (uploadStatus property) would no properly be propagated, which caused the action to succeed despite the errors.

This PR adds and explicit check for the FAILURE and NOT_FOUND uploadStatus returned by the API, to make sure those errors are properly propagated to the action.

### CODE REVIEW

**Review by mnao305 — COMMENTED** [review]
Thank you for this pull request!
I hadn't noticed the possibility of getting into `uploadStatus` without throwing an error, so that's helpful!

Could you please run `npm run format` as it seems to be causing a code style issue?

**Comment by leonluc-dev** [comment]
@mnao305 I have run npm format and updated the branch.

**Review by mnao305 — APPROVED** [review]
Thank you!

**Comment by mnao305** [comment]
Released v4.0.1
https://github.com/mnao305/chrome-extension-upload/releases/tag/v4.0.1

**Pull request merged**
