### PR TITLE
feat: add optional publish flag

### PR DESCRIPTION
**Pull request by jerry153fish**

### CODE REVIEW

**Review by mnao305 — COMMENTED** [review]
@jerry153fish 
Can you add a description of this to the README?
https://github.com/mnao305/chrome-extension-upload#input-variables

**Review by mnao305 — APPROVED** [review]
Thanks!
I'll release a version with this fix later

**Comment by mnao305** [comment]
It has been released as Version 2.1.0!
https://github.com/mnao305/chrome-extension-upload/releases/tag/2.1.0

**Comment by jerry153fish** [comment]
Thanks very much.

**Pull request merged**
