### PR TITLE
feat: `publish-target` #6

### LINKED ISSUE #6: Trusted Testerのみに公開できるようにする
つまるところのテストユーザ向けの公開。

`target`を`trustedTesters`にすれば良さそう。
https://github.com/DrewML/chrome-webstore-upload#publish-extension

### PR DESCRIPTION
**Pull request by davidp94**
Closes https://github.com/mnao305/chrome-extension-upload/issues/6

@mnao305 how can we test this branch?

### CODE REVIEW

**Comment by mnao305** [comment]
@davidp94  Thanks for this PR!

If you have created (or forked) an action, you should use it in the following format.

```
- uses: <username>/chrome-extension-upload@<branch-name>
```

This should work without having to publish it to Marketplace. You can try it with this.

We do not have test code that works completely locally. Sorry.

(I use DeepL)

**Comment by davidp94** [comment]
> @davidp94 Thanks for this PR!
> 
> If you have created (or forked) an action, you should use it in the following format.
> 
> ```
> - uses: <username>/chrome-extension-upload@<branch-name>
> ```
> 
> This should work without having to publish it to Marketplace. You can try it with this.
> 
> We do not have test code that works completely locally. Sorry.
> 
> (I use DeepL)

Tested the `trustedTesters` and it does publish with trusted testers.

Maybe can you test without setting the flag and can you check it deploys to `Public` target? @mnao305

**Comment by mnao305** [comment]
> Tested the trustedTesters and it does publish with trusted testers.

I'm not sure I understand `trustedTesters`, so thanks for testing it works!

> Maybe can you test without setting the flag and can you check it deploys to Public target?

I was able to confirm that it works without the flag set. Thank you.

**Review by mnao305 — APPROVED** [review]
Thanks!
I'll release a version with this fix later

**Pull request merged**
