### PR TITLE
Update chrome-webstore-upload

### PR DESCRIPTION
**Pull request by calvinkei**
This is to update `chrome-webstore-upload` and deprecate `client_secret`. This PR should solve #7 

There are quite a lot of eslint and typescript changes which i'm not sure if it is necessary. I have to make these changes so I can build the project by `npm run all` successfully. If you think it's best to revert to the original eslint settings, feel free to update this PR.

### CODE REVIEW

**Comment by mnao305** [comment]
@calvinkei 
Thanks for your pull request!

There is only one fix. You need to remove the `client-secret` in `action.yml`.
https://github.com/calvinkei/chrome-extension-upload/blob/master/action.yml

**Review by mnao305 — APPROVED** [review]
Thanks!
I'll release a version with this fix later

**Comment by mnao305** [comment]
It has been released as Version 2.0.0!
https://github.com/mnao305/chrome-extension-upload/releases/tag/2.0.0

**Comment by calvinkei** [comment]
@mnao305 thank you!

**Pull request merged**
